### 1. Import Dependencies

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### 2. Basic Preprocessing

In [2]:
df = pd.read_csv("data/processed/Cafe_sales_handled_outliers.csv")
df.head()

     Item  Quantity  Price Per Unit  Total Spent  Payment Method  Location
0  Coffee       2.0             2.0          4.0     Credit Card  Takeaway
1    Cake       4.0             3.0         12.0            Cash  In-store
2  Cookie       4.0             1.0          4.0     Credit Card  In-store
3   Salad       2.0             5.0         10.0  Digital Wallet  Takeaway
4  Coffee       2.0             2.0          4.0  Digital Wallet  In-store

In [3]:
Categorical_Features = ["Item","Payment Method","Location"]

Nominal_Features = ["Item","Payment Method","Location"]
Ordinal_Features = [] # There is no ordinal features because those features does not contain a specific order

### 3 . Encode Nominal Features

In [4]:
Item_dummies = pd.get_dummies(df["Item"], prefix="Item", dtype=int)
Payment_Method_dummies = pd.get_dummies(df["Payment Method"], prefix="Payment", dtype=int)
Location_dummies = pd.get_dummies(df["Location"], prefix="Location", dtype=int)

df_encoded = pd.concat([df,Item_dummies ],axis = 1)
del df_encoded["Item"]

df_encoded = pd.concat([df_encoded,Payment_Method_dummies ],axis = 1)
del df_encoded["Payment Method"]

df_encoded = pd.concat([df_encoded,Location_dummies ],axis = 1)
del df_encoded["Location"]

df_encoded

,Quantity,Price Per Unit,Total Spent,Item_Cake,Item_Coffee,Item_Cookie,Item_Juice,Item_Salad,Item_Sandwich,Item_Smoothie,Item_Tea,Payment_Cash,Payment_Credit Card,Payment_Digital Wallet,Location_In-store,Location_Takeaway
0,2.0,2.0,4.0,0,1,0,0,0,0,0,0,0,1,0,0,1
1,4.0,3.0,12.0,1,0,0,0,0,0,0,0,1,0,0,1,0
2,4.0,1.0,4.0,0,0,1,0,0,0,0,0,0,1,0,1,0
3,2.0,5.0,10.0,0,0,0,0,1,0,0,0,0,0,1,0,1
4,2.0,2.0,4.0,0,1,0,0,0,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9921,4.0,4.0,16.0,0,0,0,0,0,0,1,0,0,0,1,0,1
9922,2.0,2.0,4.0,0,1,0,0,0,0,0,0,1,0,0,0,1
9923,4.0,2.0,8.0,0,1,0,0,0,0,0,0,0,0,1,0,1
9924,3.0,1.0,3.0,0,0,1,0,0,0,0,0,0,0,1,1,0
9925,3.0,4.0,12.0,0,0,0,0,0,1,0,0,1,0,0,1,0

In [5]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9926 entries, 0 to 9925
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Quantity                9926 non-null   float64
 1   Price Per Unit          9926 non-null   float64
 2   Total Spent             9926 non-null   float64
 3   Item_Cake               9926 non-null   int64
 4   Item_Coffee             9926 non-null   int64
 5   Item_Cookie             9926 non-null   int64
 6   Item_Juice              9926 non-null   int64
 7   Item_Salad              9926 non-null   int64
 8   Item_Sandwich           9926 non-null   int64
 9   Item_Smoothie           9926 non-null   int64
 10  Item_Tea                9926 non-null   int64
 11  Payment_Cash            9926 non-null   int64
 12  Payment_Credit Card     9926 non-null   int64
 13  Payment_Digital Wallet  9926 non-null   int64
 14  Location_In-store       9926 non-null   int64
 15  Location_Takeaway       9926 non-null   int64
dtypes: float64(3), int64(13)
memory usage: 1.2 MB

In [6]:
df_encoded.to_csv("data/processed/Cafe_sales_feature_encoded.csv",index=False)