### 1. important Dependencies

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

### 2. Basic Processing

In [2]:
df = pd.read_csv("data/processed/Cafe_sales_feature_encoded.csv")
df.head()

,Quantity,Price Per Unit,Total Spent,Item_Cake,Item_Coffee,Item_Cookie,Item_Juice,Item_Salad,Item_Sandwich,Item_Smoothie,Item_Tea,Payment_Cash,Payment_Credit Card,Payment_Digital Wallet,Location_In-store,Location_Takeaway
0,2.0,2.0,4.0,False,True,False,False,False,False,False,False,False,True,False,False,True
1,4.0,3.0,12.0,True,False,False,False,False,False,False,False,True,False,False,True,False
2,4.0,1.0,4.0,False,False,True,False,False,False,False,False,False,True,False,True,False
3,2.0,5.0,10.0,False,False,False,False,True,False,False,False,False,False,True,False,True
4,2.0,2.0,4.0,False,True,False,False,False,False,False,False,False,False,True,True,False

### No need to scale this dataset because
- Very Limited Range & Discrete Values
- Already Similar Scales
- Scaling Discrete Data Issues
    - Scaling works best with continuous data  
    - With only 5 unique values, scaling might create artificial precision

- But i am scaling because of learning Purposes. After looking model accuracy i will change that according to the model

In [6]:
columns_need_to_be_scaled = ["Quantity","Price Per Unit","Total Spent"]

for col in columns_need_to_be_scaled:
    scaler = StandardScaler()
    df[col] =scaler.fit_transform(df[[col]])

In [8]:
df.head()

,Quantity,Price Per Unit,Total Spent,Item_Cake,Item_Coffee,Item_Cookie,Item_Juice,Item_Salad,Item_Sandwich,Item_Smoothie,Item_Tea,Payment_Cash,Payment_Credit Card,Payment_Digital Wallet,Location_In-store,Location_Takeaway
0,-0.720222,-0.739901,-0.820010,False,True,False,False,False,False,False,False,False,True,False,False,True
1,0.687600,0.040905,0.511593,True,False,False,False,False,False,False,False,True,False,False,True,False
2,0.687600,-1.520707,-0.820010,False,False,True,False,False,False,False,False,False,True,False,True,False
3,-0.720222,1.602517,0.178692,False,False,False,False,True,False,False,False,False,False,True,False,True
4,-0.720222,-0.739901,-0.820010,False,True,False,False,False,False,False,False,False,False,True,True,False

In [9]:
df.to_csv("data/processed/Cafe_sales_Final.csv",index=False)